In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Internship Project/Patient_Health_Records_Raw.csv")

## 1. Inspect the dataset

In [ ]:
df.head()

,Patient_ID,Name,Age,Gender,City,BMI,Blood_Pressure,Heart_Rate,Cholesterol_Level,Diabetic,Smoker,Medications,Last_Visit_Date,Follow_Up,Diagnosis_Code,Notes,Has_Disease
0,ID-00001,"SMITH, ALICE",250,Unknown,Boston,22kg/m2,120 over 80,83,190,Unknown,yes,NaN,Apr 15 2021,30,A00,Patient feeling fine 🙂,0
1,ID-00002,"SMITH, ALICE",-5,FEMALE,newyork,25.8,NaN,500,normal,N,No,NaN,2021-07-10,NaN,unknown,"BP high, needs recheck",unknown
2,ID-00003,John Doe,-5,NaN,Nwe Yrok,22kg/m2,120 - 80,500,190,no,Former,"aspirin,metformin",Apr 06 2021,30,B20,NaN,unknown
3,ID-00004,michael brown,80,F,New York,33.4,NaN,eighty,250,y,EX-smoker,NaN,20241113,30,NaN,Follow up soon,unknown
4,ID-00005,Jane Doe,250,male,la,30.1,120 over 80,0,normal,no,No,NaN,2025-09-27,NaN,I10,Patient feeling fine 🙂,1

In [ ]:
df.shape

(10000, 17)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient_ID         9493 non-null   object
 1   Name               10000 non-null  object
 2   Age                10000 non-null  object
 3   Gender             8293 non-null   object
 4   City               8997 non-null   object
 5   BMI                7582 non-null   object
 6   Blood_Pressure     7970 non-null   object
 7   Heart_Rate         10000 non-null  object
 8   Cholesterol_Level  7948 non-null   object
 9   Diabetic           8359 non-null   object
 10  Smoker             6766 non-null   object
 11  Medications        5976 non-null   object
 12  Last_Visit_Date    10000 non-null  object
 13  Follow_Up          7476 non-null   object
 14  Diagnosis_Code     8325 non-null   object
 15  Notes              5976 non-null   object
 16  Has_Disease        7480 non-null   object
dtypes: object(17)
memory usage: 1.3+ MB

In [ ]:
df.describe()

,Patient_ID,Name,Age,Gender,City,BMI,Blood_Pressure,Heart_Rate,Cholesterol_Level,Diabetic,Smoker,Medications,Last_Visit_Date,Follow_Up,Diagnosis_Code,Notes,Has_Disease
count,9493,10000,10000,8293,8997,7582,7970,10000,7948,8359,6766,5976,10000,7476,8325,5976,7480
unique,9493,5,104,5,9,202,1431,74,4,5,4,3,5816,3,5,3,3
top,ID-10000,"LEE, Sara",-5,Unknown,Chicago,22.5,120 over 80,500,190,no,EX-smoker,"aspirin,metformin",Dec 13 2020,two weeks,B20,Follow up soon,0
freq,1,2038,2537,1719,1048,2610,2066,2515,2048,1721,1739,2011,7,2540,1700,2023,2513

In [ ]:
df.columns

Index(['Patient_ID', 'Name', 'Age', 'Gender', 'City', 'BMI', 'Blood_Pressure',
       'Heart_Rate', 'Cholesterol_Level', 'Diabetic', 'Smoker', 'Medications',
       'Last_Visit_Date', 'Follow_Up', 'Diagnosis_Code', 'Notes',
       'Has_Disease'],
      dtype='object')

In [ ]:
df.isnull().sum()

Patient_ID            507
Name                    0
Age                     0
Gender               1707
City                 1003
BMI                  2418
Blood_Pressure       2030
Heart_Rate              0
Cholesterol_Level    2052
Diabetic             1641
Smoker               3234
Medications          4024
Last_Visit_Date         0
Follow_Up            2524
Diagnosis_Code       1675
Notes                4024
Has_Disease          2520
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
for col in df.select_dtypes(include="object").columns:
    print("\n", col)
    print(df[col].unique()[:30])

 Patient_ID
['ID-00001' 'ID-00002' 'ID-00003' 'ID-00004' 'ID-00005' 'ID-00006'
 'ID-00007' 'ID-00008' 'ID-00009' 'ID-00010' 'ID-00011' 'ID-00012'
 'ID-00013' 'ID-00014' 'ID-00015' 'ID-00016' 'ID-00017' 'ID-00018'
 'ID-00019' 'ID-00020' 'ID-00021' 'ID-00022' 'ID-00023' 'ID-00024'
 'ID-00025' nan 'ID-00027' 'ID-00028' 'ID-00029' 'ID-00030']

 Name
['SMITH, ALICE' 'John Doe' ' michael brown' 'Jane  Doe' 'LEE, Sara']

 Age
['250' '-5' '80' '98' 'twenty' '6' '18' '59' '46' '52' '64' '9' '100' '54'
 '85' '15' '24' '0' '21' '83' '3' '45' '48' '67' '25' '42' '99' '56' '75'
 '65']

 Gender
['Unknown' 'FEMALE' nan 'F' 'male' 'M']

 City
['Boston' 'newyork' 'Nwe Yrok' 'New York' 'la' nan 'Chicago' 'Los Angeles'
 'NY' 'chicago']

 BMI
['22kg/m2' '25.8' '33.4' '30.1' nan '22.5' '21.5' '23.2' '15.6' '21.9'
 '27.8' '24.3' '34.0' '22.2' '21.1' '22.9' '16.7' '16.0' '17.6' '20.0'
 '28.0' '32.0' '16.8' '33.6' '23.1' '31.3' '24.9' '29.3' '22.1' '24.8']

 Blood_Pressure
['120 over 80' nan '120 - 80' '120/80' '115/61' '106/68' '141/60' '91/89'
 '139/96' '124/81' '110/100' '90/74' '130/74' '115/68' '111/94' '142/80'
 '145/94' '94/98' '108/93' '121/69' '120/100' '146/74' '147/97' '94/95'
 '96/70' '132/82' '92/83' '159/96' '149/93' '133/76']

 Heart_Rate
['83' '500' 'eighty' '0' '63' '108' '85' '103' '56' '72' '90' '105' '86'
 '120' '87' '92' '114' '53' '59' '70' '112' '73' '76' '84' '51' '88' '74'
 '68' '50' '106']

 Cholesterol_Level
['190' 'normal' '250' 'high' nan]

 Diabetic
['Unknown' 'N' 'no' 'y' nan 'Yes']

 Smoker
['yes' 'No' 'Former' 'EX-smoker' nan]

 Medications
[nan 'aspirin,metformin' 'Aspirin; Metformin' 'Lisinopril / Metformin']

 Last_Visit_Date
['Apr 15 2021' '2021-07-10' 'Apr 06 2021' '20241113' '2025-09-27'
 '2025-05-22' '09/03/2024' 'May 22 2022' '02/03/2020' '2025-03-30'
 '2023-05-27' 'Apr 15 2022' 'May 27 2021' 'Sep 06 2021' '2022-09-04'
 '21/01/2024' '21/08/2022' '12/05/2020' '2021-07-06' '06/01/2021'
 'Nov 16 2020' '2024-12-03' '20220310' '2023-08-13' '2024-04-22'
 '06/12/2022' '2022-10-18' '20210715' '06/09/2025' 'Oct 28 2024']

 Follow_Up
['30' nan '14' 'two weeks']

 Diagnosis_Code
['A00' 'unknown' 'B20' nan 'I10' 'E11.9']

 Notes
['Patient feeling fine 🙂' 'BP high, needs recheck' nan 'Follow up soon']

 Has_Disease
['0' 'unknown' '1' nan]

In [ ]:
df_clean = df.copy()

In [ ]:
df_clean.shape

(10000, 17)

# 2. Standardize column names

In [ ]:
df_clean.columns

Index(['Patient_ID', 'Name', 'Age', 'Gender', 'City', 'BMI', 'Blood_Pressure',
       'Heart_Rate', 'Cholesterol_Level', 'Diabetic', 'Smoker', 'Medications',
       'Last_Visit_Date', 'Follow_Up', 'Diagnosis_Code', 'Notes',
       'Has_Disease'],
      dtype='object')

In [ ]:
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

In [ ]:
df_clean.columns.tolist()

['patient_id',
 'name',
 'age',
 'gender',
 'city',
 'bmi',
 'blood_pressure',
 'heart_rate',
 'cholesterol_level',
 'diabetic',
 'smoker',
 'medications',
 'last_visit_date',
 'follow_up',
 'diagnosis_code',
 'notes',
 'has_disease']

#3. Clean whitespace in text columns

In [ ]:
text_columns = df_clean.select_dtypes(include="object").columns

for col in text_columns:
    df_clean[col] = df_clean[col].str.strip()

In [ ]:
for col in ["name", "gender", "city", "diabetic", "smoker"]:
    print(f"\n--- {col} ---")
    print(df_clean[col].value_counts(dropna=False).head(20))

--- name ---
name
LEE, Sara        2038
SMITH, ALICE     2015
michael brown    2008
John Doe         1975
Jane  Doe        1964
Name: count, dtype: int64

--- gender ---
gender
Unknown    1719
NaN        1707
male       1703
FEMALE     1679
M          1607
F          1585
Name: count, dtype: int64

--- city ---
city
Chicago        1048
NY             1045
Boston         1023
la             1010
NaN            1003
New York       1003
Nwe Yrok        992
newyork         974
chicago         971
Los Angeles     931
Name: count, dtype: int64

--- diabetic ---
diabetic
no         1721
Yes        1689
Unknown    1660
N          1651
NaN        1641
y          1638
Name: count, dtype: int64

--- smoker ---
smoker
NaN          3234
EX-smoker    1739
Former       1718
No           1663
yes          1646
Name: count, dtype: int64

In [ ]:
df_clean = df_clean.replace(r'^\s*$', np.nan, regex=True)

In [ ]:
df_clean.isnull().sum()

patient_id            507
name                    0
age                     0
gender               1707
city                 1003
bmi                  2418
blood_pressure       2030
heart_rate              0
cholesterol_level    2052
diabetic             1641
smoker               3234
medications          4024
last_visit_date         0
follow_up            2524
diagnosis_code       1675
notes                4024
has_disease          2520
dtype: int64

## 4. Clean categorical columns

## 4.1 Clean gender

In [ ]:
df_clean["gender"] = df_clean["gender"].replace({
    "male": "Male",
    "FEMALE": "Female",
    "M": "Male",
    "F": "Female"
})

In [ ]:
df_clean["gender"].value_counts(dropna=False)

gender
Male       3310
Female     3264
Unknown    1719
NaN        1707
Name: count, dtype: int64

## 4.2 Clean diabetic

In [ ]:
df_clean["diabetic"] = df_clean["diabetic"].replace({
    "Yes": "Yes",
    "y": "Yes",
    "no": "No",
    "N": "No"
})

In [ ]:
df_clean["diabetic"].value_counts(dropna=False)

diabetic
No         3372
Yes        3327
Unknown    1660
NaN        1641
Name: count, dtype: int64

# 4.3 Clean smoker

In [ ]:
df_clean["smoker"] = df_clean["smoker"].replace({
    "yes": "Current",
    "Former": "Former",
    "EX-smoker": "Former",
    "No": "Never"
})

In [ ]:
df_clean["smoker"].value_counts(dropna=False)

smoker
Former     3457
NaN        3234
Never      1663
Current    1646
Name: count, dtype: int64

## 4.4 Clean city

In [ ]:
df_clean["city"] = df_clean["city"].replace({
    "chicago": "Chicago",
    "NY": "New York",
    "newyork": "New York",
    "Nwe Yrok": "New York",
    "la": "Los Angeles"
})

In [ ]:
df_clean["city"].value_counts(dropna=False)

city
New York       4014
Chicago        2019
Los Angeles    1941
Boston         1023
NaN            1003
Name: count, dtype: int64

# 4.5 Clean name

In [ ]:
df_clean["name"] = (
    df_clean["name"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [ ]:
df_clean["name"].value_counts()

name
LEE, Sara        2038
SMITH, ALICE     2015
michael brown    2008
John Doe         1975
Jane Doe         1964
Name: count, dtype: int64

In [ ]:
categorical_columns = [
    "gender",
    "city",
    "diabetic",
    "smoker"
]

for col in categorical_columns:
    print(f"\n{'='*40}")
    print(f"{col.upper()}")
    print(f"{'='*40}")
    print(df_clean[col].value_counts(dropna=False))

========================================
GENDER
========================================
gender
Male       3310
Female     3264
Unknown    1719
NaN        1707
Name: count, dtype: int64

========================================
CITY
========================================
city
New York       4014
Chicago        2019
Los Angeles    1941
Boston         1023
NaN            1003
Name: count, dtype: int64

========================================
DIABETIC
========================================
diabetic
No         3372
Yes        3327
Unknown    1660
NaN        1641
Name: count, dtype: int64

========================================
SMOKER
========================================
smoker
Former     3457
NaN        3234
Never      1663
Current    1646
Name: count, dtype: int64

## 4.6 Clean Age

In [ ]:
df_clean["age"].value_counts(dropna=False).head(20)

age
-5        2537
twenty    2489
250       2419
6           37
19          37
61          35
11          34
71          34
21          33
31          33
5           33
10          33
35          32
75          32
16          32
97          32
53          30
62          30
15          30
83          30
Name: count, dtype: int64

In [ ]:
print("Age data type:", df_clean["age"].dtype)
print("Minimum:", df_clean["age"].min())
print("Maximum:", df_clean["age"].max())

Age data type: object
Minimum: -5
Maximum: twenty

In [ ]:
df_clean["age"].value_counts(dropna=False)

age
-5        2537
twenty    2489
250       2419
6           37
19          37
          ...
58          18
38          18
39          17
93          16
4           15
Name: count, Length: 104, dtype: int64

In [ ]:
print("Number of unique age values:", df_clean["age"].nunique())
print("\nData types of age values:")
print(df_clean["age"].map(type).value_counts())

Number of unique age values: 104

Data types of age values:
age
<class 'str'>    10000
Name: count, dtype: int64

Convert "twenty" to 20

In [ ]:
df_clean["age"] = df_clean["age"].replace({
    "twenty": "20"
})

In [ ]:
df_clean["age"] = pd.to_numeric(
    df_clean["age"],
    errors="coerce"
)

In [ ]:
print(df_clean["age"].dtype)
print(df_clean["age"].value_counts(dropna=False).head(20))

int64
age
-5      2537
 20     2512
 250    2419
 6        37
 19       37
 61       35
 71       34
 11       34
 31       33
 5        33
 10       33
 21       33
 35       32
 16       32
 97       32
 75       32
 62       30
 53       30
 52       30
 90       30
Name: count, dtype: int64

Identify invalid ages

In [ ]:
invalid_age = (df_clean["age"] < 0) | (df_clean["age"] > 120)

print("Invalid age records:", invalid_age.sum())

Invalid age records: 4956

In [ ]:
df_clean.loc[invalid_age, "age"].value_counts()

age
-5      2537
 250    2419
Name: count, dtype: int64

Convert invalid ages to missing

In [ ]:
df_clean.loc[invalid_age, "age"] = np.nan

In [ ]:
print("Missing ages:", df_clean["age"].isna().sum())
print("Minimum valid age:", df_clean["age"].min())
print("Maximum valid age:", df_clean["age"].max())

Missing ages: 4956
Minimum valid age: 0.0
Maximum valid age: 100.0

In [ ]:
df_clean["age"].describe()

count    5044.000000
mean       35.016059
std        25.459395
min         0.000000
25%        20.000000
50%        20.000000
75%        51.000000
max       100.000000
Name: age, dtype: float64

## 4.7 Clean BMI

In [ ]:
df_clean["bmi"].value_counts(dropna=False).head(30)

bmi
22.5       2610
22kg/m2    2467
NaN        2418
19.2         23
20.2         22
17.7         22
18.5         21
24.8         21
27.8         20
34.2         20
33.1         19
29.8         19
28.6         19
27.9         18
22.4         18
19.3         18
19.6         18
21.1         18
29.0         18
16.5         17
16.4         17
15.6         17
22.9         17
21.8         17
34.6         17
23.8         17
28.7         17
21.6         17
18.1         17
22.6         17
Name: count, dtype: int64

In [ ]:
print("BMI data type:", df_clean["bmi"].dtype)

BMI data type: object

In [ ]:
print("Missing BMI:", df_clean["bmi"].isna().sum())

Missing BMI: 2418

Remove the unit

In [ ]:
df_clean["bmi"] = (
    df_clean["bmi"]
    .str.replace("kg/m2", "", regex=False)
    .str.strip()
)

In [ ]:
df_clean["bmi"].value_counts(dropna=False).head(20)

bmi
22.5    2610
22      2467
NaN     2418
19.2      23
20.2      22
17.7      22
18.5      21
24.8      21
27.8      20
34.2      20
33.1      19
29.8      19
28.6      19
27.9      18
22.4      18
19.3      18
19.6      18
21.1      18
29.0      18
16.5      17
Name: count, dtype: int64

In [ ]:
df_clean["bmi"] = pd.to_numeric(
    df_clean["bmi"],
    errors="coerce"
)

In [ ]:
print("BMI data type:", df_clean["bmi"].dtype)

BMI data type: float64

In [ ]:
df_clean["bmi"].describe()

count    7582.000000
mean       23.140992
std         3.534717
min        15.000000
25%        22.000000
50%        22.500000
75%        22.500000
max        35.000000
Name: bmi, dtype: float64

In [ ]:
print("Minimum BMI:", df_clean["bmi"].min())
print("Maximum BMI:", df_clean["bmi"].max())

Minimum BMI: 15.0
Maximum BMI: 35.0

In [ ]:
invalid_bmi = (
    (df_clean["bmi"] < 10) |
    (df_clean["bmi"] > 80)
)

print("Invalid BMI records:", invalid_bmi.sum())

Invalid BMI records: 0

In [ ]:
df_clean["bmi"].describe()

count    7582.000000
mean       23.140992
std         3.534717
min        15.000000
25%        22.000000
50%        22.500000
75%        22.500000
max        35.000000
Name: bmi, dtype: float64

In [ ]:
print("Invalid BMI records:", invalid_bmi.sum())

Invalid BMI records: 0

### 4.8 Clean Blood Pressure

In [ ]:
df_clean["blood_pressure"].value_counts(dropna=False).head(30)

blood_pressure
120 over 80    2066
NaN            2030
120/80         1987
120 - 80       1957
148/86            4
96/79             4
115/67            4
92/85             4
118/64            4
133/63            4
129/77            4
110/75            4
130/82            4
91/100            4
135/88            4
124/71            4
121/89            4
143/96            4
152/62            3
113/78            3
146/94            3
131/66            3
133/60            3
128/84            3
117/64            3
91/78             3
141/79            3
111/99            3
152/79            3
114/72            3
Name: count, dtype: int64

In [ ]:
print("Data type:", df_clean["blood_pressure"].dtype)
print("Missing:", df_clean["blood_pressure"].isna().sum())

Data type: object
Missing: 2030

# Standardize the BP separator

In [ ]:
df_clean["blood_pressure"] = (
    df_clean["blood_pressure"]
    .str.replace(" over ", "/", regex=False)
    .str.replace(" - ", "/", regex=False)
)

In [ ]:
df_clean["blood_pressure"].value_counts(dropna=False).head(15)

blood_pressure
120/80    6010
NaN       2030
118/64       4
110/75       4
148/86       4
124/71       4
96/79        4
92/85        4
133/63       4
129/77       4
143/96       4
115/67       4
130/82       4
121/89       4
135/88       4
Name: count, dtype: int64

Split Blood Pressure

In [ ]:
bp_split = df_clean["blood_pressure"].str.split("/", expand=True)

df_clean["systolic_bp"] = pd.to_numeric(bp_split[0], errors="coerce")
df_clean["diastolic_bp"] = pd.to_numeric(bp_split[1], errors="coerce")

In [ ]:
df_clean[[
    "blood_pressure",
    "systolic_bp",
    "diastolic_bp"
]].head(20)

   blood_pressure  systolic_bp  diastolic_bp
0          120/80        120.0          80.0
1             NaN          NaN           NaN
2          120/80        120.0          80.0
3             NaN          NaN           NaN
4          120/80        120.0          80.0
5          120/80        120.0          80.0
6          120/80        120.0          80.0
7          120/80        120.0          80.0
8          120/80        120.0          80.0
9             NaN          NaN           NaN
10         120/80        120.0          80.0
11         120/80        120.0          80.0
12         115/61        115.0          61.0
13         120/80        120.0          80.0
14         120/80        120.0          80.0
15         120/80        120.0          80.0
16         120/80        120.0          80.0
17         120/80        120.0          80.0
18         106/68        106.0          68.0
19         120/80        120.0          80.0

In [ ]:
print("Systolic BP")
print(df_clean["systolic_bp"].describe())

print("\nDiastolic BP")
print(df_clean["diastolic_bp"].describe())

Systolic BP
count    7970.000000
mean      121.146173
std        10.434089
min        90.000000
25%       120.000000
50%       120.000000
75%       120.000000
max       160.000000
Name: systolic_bp, dtype: float64

Diastolic BP
count    7970.000000
mean       79.990841
std         5.925441
min        60.000000
25%        80.000000
50%        80.000000
75%        80.000000
max       100.000000
Name: diastolic_bp, dtype: float64

In [ ]:
print("Missing systolic:", df_clean["systolic_bp"].isna().sum())
print("Missing diastolic:", df_clean["diastolic_bp"].isna().sum())

Missing systolic: 2030
Missing diastolic: 2030

In [ ]:
invalid_systolic = (
    (df_clean["systolic_bp"] < 70) |
    (df_clean["systolic_bp"] > 250)
)

invalid_diastolic = (
    (df_clean["diastolic_bp"] < 40) |
    (df_clean["diastolic_bp"] > 150)
)

print("Invalid systolic values:", invalid_systolic.sum())
print("Invalid diastolic values:", invalid_diastolic.sum())

Invalid systolic values: 0
Invalid diastolic values: 0

In [ ]:
bp_logic_issue = (
    df_clean["diastolic_bp"] >= df_clean["systolic_bp"]
)

print("BP logical issues:", bp_logic_issue.sum())

df_clean.loc[
    bp_logic_issue,
    ["blood_pressure", "systolic_bp", "diastolic_bp"]
].head(20)

BP logical issues: 58

     blood_pressure  systolic_bp  diastolic_bp
58            94/98         94.0          98.0
83            94/95         94.0          95.0
366           92/94         92.0          94.0
816           92/92         92.0          92.0
933          92/100         92.0         100.0
1070          91/97         91.0          97.0
1184          90/97         90.0          97.0
1288          92/99         92.0          99.0
1305          92/99         92.0          99.0
1448          90/98         90.0          98.0
1470          92/94         92.0          94.0
1609          90/98         90.0          98.0
1826          95/96         95.0          96.0
2025          94/96         94.0          96.0
2187          90/98         90.0          98.0
2206          93/98         93.0          98.0
2337          93/93         93.0          93.0
2400         91/100         91.0         100.0
2512          95/97         95.0          97.0
2594          95/95         95.0          95.0

In [ ]:
df_clean.loc[
    bp_logic_issue,
    ["blood_pressure", "systolic_bp", "diastolic_bp"]
].value_counts()

blood_pressure  systolic_bp  diastolic_bp
91/100          91.0         100.0           4
90/98           90.0         98.0            3
94/94           94.0         94.0            3
92/92           92.0         92.0            3
91/92           91.0         92.0            2
92/94           92.0         94.0            2
90/95           90.0         95.0            2
92/99           92.0         99.0            2
95/97           95.0         97.0            2
97/100          97.0         100.0           2
93/97           93.0         97.0            2
94/98           94.0         98.0            2
91/97           91.0         97.0            2
90/90           90.0         90.0            1
90/93           90.0         93.0            1
90/94           90.0         94.0            1
90/97           90.0         97.0            1
90/92           90.0         92.0            1
92/100          92.0         100.0           1
93/93           93.0         93.0            1
93/95           93.0         95.0            1
91/98           91.0         98.0            1
93/94           93.0         94.0            1
91/95           91.0         95.0            1
94/96           94.0         96.0            1
94/95           94.0         95.0            1
93/98           93.0         98.0            1
95/95           95.0         95.0            1
95/96           95.0         96.0            1
96/96           96.0         96.0            1
96/97           96.0         97.0            1
94/99           94.0         99.0            1
96/98           96.0         98.0            1
96/99           96.0         99.0            1
97/97           97.0         97.0            1
98/100          98.0         100.0           1
98/98           98.0         98.0            1
98/99           98.0         99.0            1
99/100          99.0         100.0           1
99/99           99.0         99.0            1
Name: count, dtype: int64

In [ ]:
df_clean.loc[
    bp_logic_issue,
    ["blood_pressure", "systolic_bp", "diastolic_bp"]
].head(20)

     blood_pressure  systolic_bp  diastolic_bp
58            94/98         94.0          98.0
83            94/95         94.0          95.0
366           92/94         92.0          94.0
816           92/92         92.0          92.0
933          92/100         92.0         100.0
1070          91/97         91.0          97.0
1184          90/97         90.0          97.0
1288          92/99         92.0          99.0
1305          92/99         92.0          99.0
1448          90/98         90.0          98.0
1470          92/94         92.0          94.0
1609          90/98         90.0          98.0
1826          95/96         95.0          96.0
2025          94/96         94.0          96.0
2187          90/98         90.0          98.0
2206          93/98         93.0          98.0
2337          93/93         93.0          93.0
2400         91/100         91.0         100.0
2512          95/97         95.0          97.0
2594          95/95         95.0          95.0

Mark the 58 readings as missing

In [ ]:
df_clean.loc[bp_logic_issue, "systolic_bp"] = np.nan
df_clean.loc[bp_logic_issue, "diastolic_bp"] = np.nan

In [ ]:
print("Missing systolic:", df_clean["systolic_bp"].isna().sum())
print("Missing diastolic:", df_clean["diastolic_bp"].isna().sum())

Missing systolic: 2088
Missing diastolic: 2088

In [ ]:
bp_logic_check = (
    df_clean["diastolic_bp"] >= df_clean["systolic_bp"]
)

print("Remaining BP logical issues:", bp_logic_check.sum())

Remaining BP logical issues: 0

## 4.9 Clean heartrate

In [ ]:
print(df_clean["heart_rate"].value_counts(dropna=False).head(20))
print("\nData type:", df_clean["heart_rate"].dtype)
print("\nStatistics:")
print(pd.to_numeric(df_clean["heart_rate"], errors="coerce").describe())

heart_rate
500       2515
eighty    2459
0         2452
85          50
109         50
79          49
107         49
63          48
120         47
106         45
89          45
119         45
105         44
67          43
76          43
104         43
95          43
94          42
54          42
115         42
Name: count, dtype: int64

Data type: object

Statistics:
count    7541.000000
mean      195.882376
std       218.275943
min         0.000000
25%         0.000000
50%        87.000000
75%       500.000000
max       500.000000
Name: heart_rate, dtype: float64

Convert "eighty" and make Heart Rate numeric

In [ ]:
df_clean["heart_rate"] = df_clean["heart_rate"].replace({
    "eighty": "80"
})

df_clean["heart_rate"] = pd.to_numeric(
    df_clean["heart_rate"],
    errors="coerce"
)

print(df_clean["heart_rate"].describe())
print("\nData type:", df_clean["heart_rate"].dtype)

count    10000.000000
mean       167.386900
std        196.004697
min          0.000000
25%         51.000000
50%         80.000000
75%        500.000000
max        500.000000
Name: heart_rate, dtype: float64

Data type: int64

In [ ]:
invalid_heart_rate = (
    (df_clean["heart_rate"] < 30) |
    (df_clean["heart_rate"] > 220)
)

print("Invalid heart rate values:", invalid_heart_rate.sum())
print("\nInvalid value counts:")
print(df_clean.loc[
    invalid_heart_rate,
    "heart_rate"
].value_counts())

Invalid heart rate values: 4967

Invalid value counts:
heart_rate
500    2515
0      2452
Name: count, dtype: int64

Handle invalid heart rates

In [ ]:
df_clean.loc[invalid_heart_rate, "heart_rate"] = np.nan

In [ ]:
print("Missing heart rate:", df_clean["heart_rate"].isna().sum())

print("\nHeart rate statistics:")
print(df_clean["heart_rate"].describe())

Missing heart rate: 4967

Heart rate statistics:
count    5033.000000
mean       82.727797
std        14.975119
min        50.000000
25%        80.000000
50%        80.000000
75%        87.000000
max       120.000000
Name: heart_rate, dtype: float64

In [ ]:
remaining_invalid_hr = (
    (df_clean["heart_rate"] < 30) |
    (df_clean["heart_rate"] > 220)
)

print("Remaining invalid heart rates:", remaining_invalid_hr.sum())

Remaining invalid heart rates: 0

## 4.10 Clean Cholesterol Level

In [ ]:
print(df_clean["cholesterol_level"].value_counts(dropna=False).head(30))

print("\nData type:", df_clean["cholesterol_level"].dtype)

print("\nNumeric conversion statistics:")
print(pd.to_numeric(
    df_clean["cholesterol_level"],
    errors="coerce"
).describe())

cholesterol_level
NaN       2052
190       2048
normal    1994
250       1970
high      1936
Name: count, dtype: int64

Data type: object

Numeric conversion statistics:
count    4018.000000
mean      219.417621
std        29.998080
min       190.000000
25%       190.000000
50%       190.000000
75%       250.000000
max       250.000000
Name: cholesterol_level, dtype: float64

Create the cholesterol category

In [ ]:
df_clean["cholesterol_category"] = df_clean["cholesterol_level"].replace({
    "normal": "Normal",
    "high": "High"
})

print(df_clean["cholesterol_category"].value_counts(dropna=False))

cholesterol_category
NaN       2052
190       2048
Normal    1994
250       1970
High      1936
Name: count, dtype: int64

In [ ]:
df_clean["cholesterol_level"] = pd.to_numeric(
    df_clean["cholesterol_level"],
    errors="coerce"
)

print(df_clean["cholesterol_level"].value_counts(dropna=False))
print("\nData type:", df_clean["cholesterol_level"].dtype)

cholesterol_level
NaN      5982
190.0    2048
250.0    1970
Name: count, dtype: int64

Data type: float64

In [ ]:
df_clean.loc[
    df_clean["cholesterol_category"].isin(["190", "250", 190, 250]),
    "cholesterol_category"
] = np.nan

print(df_clean["cholesterol_category"].value_counts(dropna=False))

cholesterol_category
NaN       6070
Normal    1994
High      1936
Name: count, dtype: int64

In [ ]:
invalid_cholesterol = (
    (df_clean["cholesterol_level"] < 100) |
    (df_clean["cholesterol_level"] > 400)
)

print("Invalid cholesterol values:", invalid_cholesterol.sum())

Invalid cholesterol values: 0

In [ ]:
print(df_clean["cholesterol_level"].describe())

count    4018.000000
mean      219.417621
std        29.998080
min       190.000000
25%       190.000000
50%       190.000000
75%       250.000000
max       250.000000
Name: cholesterol_level, dtype: float64

In [ ]:
print(df_clean["cholesterol_category"].value_counts(dropna=False))

cholesterol_category
NaN       6070
Normal    1994
High      1936
Name: count, dtype: int64

## 4.11 Medications

In [ ]:
print(df_clean["medications"].value_counts(dropna=False).head(30))

medications
NaN                       4024
aspirin,metformin         2011
Lisinopril / Metformin    2011
Aspirin; Metformin        1954
Name: count, dtype: int64

In [ ]:
print(df_clean["medications"].dropna().head(20).to_string(index=False))

     aspirin,metformin
     aspirin,metformin
    Aspirin; Metformin
     aspirin,metformin
Lisinopril / Metformin
    Aspirin; Metformin
    Aspirin; Metformin
     aspirin,metformin
     aspirin,metformin
    Aspirin; Metformin
Lisinopril / Metformin
    Aspirin; Metformin
     aspirin,metformin
    Aspirin; Metformin
    Aspirin; Metformin
     aspirin,metformin
     aspirin,metformin
Lisinopril / Metformin
Lisinopril / Metformin
     aspirin,metformin

Standardize separators and capitalization

In [ ]:
df_clean["medications"] = (
    df_clean["medications"]
    .str.replace(";", ",", regex=False)
    .str.replace("/", ",", regex=False)
    .str.replace(r"\s*,\s*", ", ", regex=True)
    .str.strip()
)

In [ ]:
df_clean["medications"] = df_clean["medications"].replace({
    "aspirin, metformin": "Aspirin, Metformin",
    "Aspirin, Metformin": "Aspirin, Metformin",
    "Lisinopril, Metformin": "Lisinopril, Metformin"
})

In [ ]:
print(df_clean["medications"].value_counts(dropna=False))

medications
NaN                      4024
Aspirin, Metformin       3965
Lisinopril, Metformin    2011
Name: count, dtype: int64

### 4.12 last_visit_date

In [ ]:
print(df_clean["last_visit_date"].value_counts().head(20))

print("\nData type:", df_clean["last_visit_date"].dtype)

print("\nSample values:")
print(df_clean["last_visit_date"].head(20).to_string(index=False))

last_visit_date
Dec 13 2020    7
2021-06-24     6
07/08/2024     6
21/04/2024     6
20210629       6
Mar 19 2023    6
20220410       6
20200301       6
2021-10-19     6
2021-09-09     6
2024-11-17     6
20200706       6
20210611       6
13/12/2020     6
Oct 10 2021    6
2021-03-04     5
2025-01-18     5
27/07/2023     5
2020-11-12     5
20221117       5
Name: count, dtype: int64

Data type: object

Sample values:
Apr 15 2021
 2021-07-10
Apr 06 2021
   20241113
 2025-09-27
 2025-05-22
 09/03/2024
May 22 2022
 02/03/2020
 2025-03-30
 2023-05-27
Apr 15 2022
May 27 2021
Sep 06 2021
 2022-09-04
 21/01/2024
 21/08/2022
 12/05/2020
 2021-07-06
 06/01/2021

Convert to datetime

In [ ]:
df_clean["last_visit_date"] = pd.to_datetime(
    df_clean["last_visit_date"],
    errors="coerce",
    dayfirst=True
)

In [ ]:
print("Data type:", df_clean["last_visit_date"].dtype)

print("\nMissing dates:", df_clean["last_visit_date"].isna().sum())

print("\nDate range:")
print("Earliest:", df_clean["last_visit_date"].min())
print("Latest:", df_clean["last_visit_date"].max())

print("\nSample:")
print(df_clean["last_visit_date"].head(20))

Data type: datetime64[ns]

Missing dates: 7508

Date range:
Earliest: 2020-01-01 00:00:00
Latest: 2025-10-01 00:00:00

Sample:
0    2021-04-15
1           NaT
2    2021-04-06
3           NaT
4           NaT
5           NaT
6           NaT
7    2022-05-22
8           NaT
9           NaT
10          NaT
11   2022-04-15
12   2021-05-27
13   2021-09-06
14          NaT
15          NaT
16          NaT
17          NaT
18          NaT
19          NaT
Name: last_visit_date, dtype: datetime64[ns]

In [ ]:
print(df.columns.tolist())

['Patient_ID', 'Name', 'Age', 'Gender', 'City', 'BMI', 'Blood_Pressure', 'Heart_Rate', 'Cholesterol_Level', 'Diabetic', 'Smoker', 'Medications', 'Last_Visit_Date', 'Follow_Up', 'Diagnosis_Code', 'Notes', 'Has_Disease']

In [ ]:
df_clean["last_visit_date"] = df["Last_Visit_Date"].copy()

In [ ]:
date = df_clean["last_visit_date"].astype(str).str.strip()

parsed_date = pd.Series(
    pd.NaT,
    index=df_clean.index,
    dtype="datetime64[ns]"
)

# YYYY-MM-DD
mask_iso = date.str.match(r"^\d{4}-\d{2}-\d{2}$")
parsed_date.loc[mask_iso] = pd.to_datetime(
    date.loc[mask_iso],
    format="%Y-%m-%d",
    errors="coerce"
)

# Apr 15 2021
mask_text = date.str.match(r"^[A-Za-z]{3} \d{2} \d{4}$")
parsed_date.loc[mask_text] = pd.to_datetime(
    date.loc[mask_text],
    format="%b %d %Y",
    errors="coerce"
)

# YYYYMMDD
mask_compact = date.str.match(r"^\d{8}$")
parsed_date.loc[mask_compact] = pd.to_datetime(
    date.loc[mask_compact],
    format="%Y%m%d",
    errors="coerce"
)

# DD/MM/YYYY
mask_slash = date.str.match(r"^\d{2}/\d{2}/\d{4}$")
parsed_date.loc[mask_slash] = pd.to_datetime(
    date.loc[mask_slash],
    format="%d/%m/%Y",
    errors="coerce"
)

df_clean["last_visit_date"] = parsed_date

In [ ]:
print("Missing dates:", df_clean["last_visit_date"].isna().sum())
print("Data type:", df_clean["last_visit_date"].dtype)
print("Earliest:", df_clean["last_visit_date"].min())
print("Latest:", df_clean["last_visit_date"].max())

Missing dates: 0
Data type: datetime64[ns]
Earliest: 2020-01-01 00:00:00
Latest: 2025-10-01 00:00:00

## 4.13 follow_up

In [ ]:
print(df_clean["follow_up"].value_counts(dropna=False).head(30))

print("\nData type:", df_clean["follow_up"].dtype)

print("\nSample values:")
print(df_clean["follow_up"].dropna().head(20).to_string(index=False))

follow_up
two weeks    2540
NaN          2524
30           2474
14           2462
Name: count, dtype: int64

Data type: object

Sample values:
       30
       30
       30
       30
       30
       30
       30
       14
       14
       30
two weeks
       30
       30
       30
two weeks
       30
       14
       14
two weeks
       30

Convert follow_up to days

In [ ]:
df_clean["follow_up"] = df_clean["follow_up"].replace({
    "two weeks": "14"
})

df_clean["follow_up"] = pd.to_numeric(
    df_clean["follow_up"],
    errors="coerce"
)

In [ ]:
print(df_clean["follow_up"].value_counts(dropna=False))

print("\nData type:", df_clean["follow_up"].dtype)

print("\nStatistics:")
print(df_clean["follow_up"].describe())

follow_up
14.0    5002
NaN     2524
30.0    2474
Name: count, dtype: int64

Data type: float64

Statistics:
count    7476.000000
mean       19.294810
std         7.529245
min        14.000000
25%        14.000000
50%        14.000000
75%        30.000000
max        30.000000
Name: follow_up, dtype: float64

## 4.14 diagnosis_code

In [ ]:
print(df_clean["diagnosis_code"].value_counts(dropna=False).head(30))

print("\nData type:", df_clean["diagnosis_code"].dtype)

print("\nSample values:")
print(df_clean["diagnosis_code"].dropna().head(30).to_string(index=False))

diagnosis_code
B20        1700
unknown    1691
NaN        1675
I10        1664
E11.9      1663
A00        1607
Name: count, dtype: int64

Data type: object

Sample values:
    A00
unknown
    B20
    I10
  E11.9
  E11.9
    I10
unknown
    A00
unknown
unknown
  E11.9
    I10
    I10
  E11.9
  E11.9
  E11.9
    B20
    I10
unknown
unknown
    B20
unknown
    I10
  E11.9
    I10
  E11.9
    A00
    A00
unknown

In [ ]:
# Standardize diagnosis code text
df_clean["diagnosis_code"] = df_clean["diagnosis_code"].str.strip()

# Treat "unknown" as missing/unknown
df_clean["diagnosis_code"] = df_clean["diagnosis_code"].replace(
    {"unknown": np.nan}
)

# Validate diagnosis code format
valid_diagnosis = df_clean["diagnosis_code"].str.match(
    r"^[A-Z]\d{2}(\.\d+)?$",
    na=False
)

# Count invalid diagnosis codes
print("Invalid diagnosis codes:", (~valid_diagnosis & df_clean["diagnosis_code"].notna()).sum())

# Convert invalid codes to NaN
df_clean.loc[
    (~valid_diagnosis) & df_clean["diagnosis_code"].notna(),
    "diagnosis_code"
] = np.nan

Invalid diagnosis codes: 0

In [ ]:
print(df_clean["diagnosis_code"].value_counts(dropna=False))

print("\nData type:", df_clean["diagnosis_code"].dtype)

print("\nRemaining invalid codes:")
print(
    df_clean.loc[
        df_clean["diagnosis_code"].notna() &
        ~df_clean["diagnosis_code"].str.match(
            r"^[A-Z]\d{2}(\.\d+)?$",
            na=False
        ),
        "diagnosis_code"
    ].unique()
)

diagnosis_code
NaN      3366
B20      1700
I10      1664
E11.9    1663
A00      1607
Name: count, dtype: int64

Data type: object

Remaining invalid codes:
[]

# 4.15 Clean notes

In [ ]:
# Remove notes column
df_clean = df_clean.drop(columns=["notes"])

# Check the result
print("Final shape:", df_clean.shape)
print("\nFinal columns:")
print(df_clean.columns.tolist())

Final shape: (10000, 19)

Final columns:
['patient_id', 'name', 'age', 'gender', 'city', 'bmi', 'blood_pressure', 'heart_rate', 'cholesterol_level', 'diabetic', 'smoker', 'medications', 'last_visit_date', 'follow_up', 'diagnosis_code', 'has_disease', 'systolic_bp', 'diastolic_bp', 'cholesterol_category']

In [ ]:
print("notes" in df_clean.columns)

False

## 4.16 Clean has_disease

In [ ]:
print(df_clean["has_disease"].value_counts(dropna=False))

print("\nData type:", df_clean["has_disease"].dtype)

print("\nSample values:")
print(df_clean["has_disease"].dropna().head(30).to_string(index=False))

has_disease
NaN        2520
0          2513
unknown    2506
1          2461
Name: count, dtype: int64

Data type: object

Sample values:
      0
unknown
unknown
unknown
      1
      0
unknown
unknown
      0
      1
      1
      0
unknown
      1
      0
      0
unknown
      0
      0
      1
unknown
      1
unknown
unknown
      0
unknown
      0
unknown
unknown
      1

In [ ]:
# Convert has_disease to numeric
df_clean["has_disease"] = pd.to_numeric(
    df_clean["has_disease"].replace("unknown", np.nan),
    errors="coerce"
)

In [ ]:
print(df_clean["has_disease"].value_counts(dropna=False))

print("\nData type:", df_clean["has_disease"].dtype)

print("\nUnique values:")
print(df_clean["has_disease"].unique())

has_disease
NaN    5026
0.0    2513
1.0    2461
Name: count, dtype: int64

Data type: float64

Unique values:
[ 0. nan  1.]

## 5. Final validation

In [ ]:
print("Dataset shape:", df_clean.shape)

print("\nData types:")
print(df_clean.dtypes)

print("\nMissing values:")
print(df_clean.isna().sum())

print("\nTotal missing values:", df_clean.isna().sum().sum())

Dataset shape: (10000, 20)

Data types:
patient_id                      object
name                            object
age                            float64
gender                          object
city                            object
bmi                            float64
blood_pressure                  object
heart_rate                     float64
cholesterol_level              float64
diabetic                        object
smoker                          object
medications                     object
last_visit_date         datetime64[ns]
follow_up                      float64
diagnosis_code                  object
notes                           object
has_disease                    float64
systolic_bp                    float64
diastolic_bp                   float64
cholesterol_category            object
dtype: object

Missing values:
patient_id               507
name                       0
age                     4956
gender                  1707
city                    1003
bmi                     2418
blood_pressure          2030
heart_rate              4967
cholesterol_level       5982
diabetic                1641
smoker                  3234
medications             4024
last_visit_date            0
follow_up               2524
diagnosis_code          3366
notes                   4024
has_disease             5026
systolic_bp             2088
diastolic_bp            2088
cholesterol_category    6070
dtype: int64

Total missing values: 57655

In [ ]:
print("Duplicate rows:", df_clean.duplicated().sum())

Duplicate rows: 0

In [ ]:
print("Age range:",
      df_clean["age"].min(),
      "to",
      df_clean["age"].max())

print("BMI range:",
      df_clean["bmi"].min(),
      "to",
      df_clean["bmi"].max())

print("Heart rate range:",
      df_clean["heart_rate"].min(),
      "to",
      df_clean["heart_rate"].max())

print("Systolic BP range:",
      df_clean["systolic_bp"].min(),
      "to",
      df_clean["systolic_bp"].max())

print("Diastolic BP range:",
      df_clean["diastolic_bp"].min(),
      "to",
      df_clean["diastolic_bp"].max())

print("Cholesterol range:",
      df_clean["cholesterol_level"].min(),
      "to",
      df_clean["cholesterol_level"].max())

print("Follow-up range:",
      df_clean["follow_up"].min(),
      "to",
      df_clean["follow_up"].max())

Age range: 0.0 to 100.0
BMI range: 15.0 to 35.0
Heart rate range: 50.0 to 120.0
Systolic BP range: 90.0 to 160.0
Diastolic BP range: 60.0 to 100.0
Cholesterol range: 190.0 to 250.0
Follow-up range: 14.0 to 30.0

In [ ]:
df_clean["smoker"] = df_clean["smoker"].replace({
    "yes": "Current",
    "Former": "Former",
    "EX-smoker": "Former",
    "No": "Never"
})

In [ ]:
print(df_clean["smoker"].value_counts(dropna=False))

smoker
Former     3457
NaN        3234
Never      1663
Current    1646
Name: count, dtype: int64

## 6. Final smoker validation

In [ ]:
print(df_clean["smoker"].value_counts(dropna=False))

smoker
Former     3457
NaN        3234
Never      1663
Current    1646
Name: count, dtype: int64

## 7. Final Data Quality Report

In [ ]:
print("=" * 50)
print("FINAL DATA QUALITY REPORT")
print("=" * 50)

print("Dataset shape:", df_clean.shape)
print("Duplicate rows:", df_clean.duplicated().sum())
print("Total missing values:", df_clean.isna().sum().sum())

print("\nMissing values by column:")
print(df_clean.isna().sum())

print("\nData types:")
print(df_clean.dtypes)

print("\nNumeric ranges:")
print("Age:", df_clean["age"].min(), "-", df_clean["age"].max())
print("BMI:", df_clean["bmi"].min(), "-", df_clean["bmi"].max())
print("Heart Rate:", df_clean["heart_rate"].min(), "-", df_clean["heart_rate"].max())
print("Systolic BP:", df_clean["systolic_bp"].min(), "-", df_clean["systolic_bp"].max())
print("Diastolic BP:", df_clean["diastolic_bp"].min(), "-", df_clean["diastolic_bp"].max())
print("Cholesterol:", df_clean["cholesterol_level"].min(), "-", df_clean["cholesterol_level"].max())

==================================================
FINAL DATA QUALITY REPORT
==================================================
Dataset shape: (10000, 19)
Duplicate rows: 0
Total missing values: 53631

Missing values by column:
patient_id               507
name                       0
age                     4956
gender                  1707
city                    1003
bmi                     2418
blood_pressure          2030
heart_rate              4967
cholesterol_level       5982
diabetic                1641
smoker                  3234
medications             4024
last_visit_date            0
follow_up               2524
diagnosis_code          3366
has_disease             5026
systolic_bp             2088
diastolic_bp            2088
cholesterol_category    6070
dtype: int64

Data types:
patient_id                      object
name                            object
age                            float64
gender                          object
city                            object
bmi                            float64
blood_pressure                  object
heart_rate                     float64
cholesterol_level              float64
diabetic                        object
smoker                          object
medications                     object
last_visit_date         datetime64[ns]
follow_up                      float64
diagnosis_code                  object
has_disease                    float64
systolic_bp                    float64
diastolic_bp                   float64
cholesterol_category            object
dtype: object

Numeric ranges:
Age: 0.0 - 100.0
BMI: 15.0 - 35.0
Heart Rate: 50.0 - 120.0
Systolic BP: 90.0 - 160.0
Diastolic BP: 60.0 - 100.0
Cholesterol: 190.0 - 250.0

# 8. Export the cleaned dataset

In [ ]:
# Export cleaned dataset
output_file = "Patient_Health_Records_Cleaned.csv"

df_clean.to_csv(output_file, index=False)

print(f"Cleaned dataset saved as: {output_file}")
print(f"Shape: {df_clean.shape}")

Cleaned dataset saved as: Patient_Health_Records_Cleaned.csv
Shape: (10000, 19)

In [ ]:
from google.colab import files

files.download("Patient_Health_Records_Cleaned.csv")